/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BillText: typeof import('./../src/components/basic/BillText.vue')['default']
    CustomDatePicker: typeof import('./../src/components/form/CustomDatePicker.vue')['default']
    CustomEchart: typeof import('./../src/components/basic/CustomEchart.vue')['default']
    CustomForm: typeof import('./../src/components/form/CustomForm.vue')['default']
    CustomFormItem: typeof import('./../src/components/form/CustomFormItem.vue')['default']
    CustomInput: typeof import('./../src/components/form/CustomInput.vue')['default']
    CustomInputNumber: typeof import('./../src/components/form/CustomInputNumber.vue')['default']
    CustomPagination: typeof import('./../src/components/basic/CustomPagination.vue')['default']
    CustomQueryHead: typeof import('./../src/components/basic/CustomQueryHead.vue')['default']
    CustomQueryHeader: typeof import('./../src/components/basic/CustomQueryHeader.vue')['default']
    CustomQueryPage: typeof import('./../src/components/basic/CustomQueryPage.vue')['default']
    CustomSelect: typeof import('./../src/components/form/CustomSelect.vue')['default']
    CustomTable: typeof import('./../src/components/basic/CustomTable.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    IEpExpand: typeof import('~icons/ep/expand')['default']
    LeftMenu: typeof import('./../src/components/basic/LeftMenu.vue')['default']
    PageContent: typeof import('./../src/components/basic/PageContent.vue')['default']
    PageHeader: typeof import('./../src/components/basic/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
